// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhjalJBsbZzGA0WoRSMP4iTU68fSJw0M',
    appId: '1:356333598974:web:f93c335bd6041852d00daf',
    messagingSenderId: '356333598974',
    projectId: 'recording-app-877d8',
    authDomain: 'recording-app-877d8.firebaseapp.com',
    storageBucket: 'recording-app-877d8.firebasestorage.app',
    measurementId: 'G-07SXKLR3Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcjw_0hsRhvQPRmlyKe7R4_cdCl9fJ3t0',
    appId: '1:356333598974:android:6a6f9af8e3744eaad00daf',
    messagingSenderId: '356333598974',
    projectId: 'recording-app-877d8',
    storageBucket: 'recording-app-877d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGK9q2YsdYMgBSFk7nX6mldvwV_gr_JZA',
    appId: '1:356333598974:ios:6128e6fda62bafc2d00daf',
    messagingSenderId: '356333598974',
    projectId: 'recording-app-877d8',
    storageBucket: 'recording-app-877d8.firebasestorage.app',
    iosBundleId: 'com.example.utsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGK9q2YsdYMgBSFk7nX6mldvwV_gr_JZA',
    appId: '1:356333598974:ios:6128e6fda62bafc2d00daf',
    messagingSenderId: '356333598974',
    projectId: 'recording-app-877d8',
    storageBucket: 'recording-app-877d8.firebasestorage.app',
    iosBundleId: 'com.example.utsProject',
  );
}
